
import { SlitherSkin, SlitherAccessory } from '../types';

export const SLITHER_SKINS_CATALOG: SlitherSkin[] = [
    { id: 'ss_cyan', name: 'Cyan Néon', price: 0, primaryColor: '#00f3ff', secondaryColor: '#0088ff', glowColor: '#00f3ff', pattern: 'solid', rarity: 'COMMON', description: 'Le look original.' },
    { id: 'ss_pink', name: 'Rose Flash', price: 200, primaryColor: '#ff00ff', secondaryColor: '#cc00cc', glowColor: '#ff00ff', pattern: 'solid', rarity: 'COMMON', description: 'Vibrant et assumé.' },
    { id: 'ss_lime', name: 'Lime Toxique', price: 200, primaryColor: '#ccff00', secondaryColor: '#88aa00', glowColor: '#ccff00', pattern: 'solid', rarity: 'COMMON', description: 'Attention, corrosif !' },
    { id: 'ss_orange', name: 'Orange Feu', price: 200, primaryColor: '#ff9d00', secondaryColor: '#cc6600', glowColor: '#ff9d00', pattern: 'solid', rarity: 'COMMON', description: 'Chaleur intense.' },
    { id: 'ss_purple', name: 'Violet Royal', price: 200, primaryColor: '#9d00ff', secondaryColor: '#6600cc', glowColor: '#9d00ff', pattern: 'solid', rarity: 'COMMON', description: 'Mystique.' },
    { id: 'ss_red', name: 'Rouge Sang', price: 200, primaryColor: '#ff4d4d', secondaryColor: '#990000', glowColor: '#ff4d4d', pattern: 'solid', rarity: 'COMMON', description: 'Agressif.' },
    { id: 'ss_yellow', name: 'Jaune Solaire', price: 200, primaryColor: '#ffe600', secondaryColor: '#aa9900', glowColor: '#ffe600', pattern: 'solid', rarity: 'COMMON', description: 'Brillant.' },
    { id: 'ss_white', name: 'Blanc Pur', price: 500, primaryColor: '#ffffff', secondaryColor: '#cccccc', glowColor: '#ffffff', pattern: 'solid', rarity: 'COMMON', description: 'Éclat céleste.' },
    { id: 'ss_steel', name: 'Acier Poli', price: 750, primaryColor: '#94a3b8', secondaryColor: '#475569', glowColor: '#ffffff', pattern: 'metallic', rarity: 'RARE', description: 'Reflets industriels.' },
    { id: 'ss_gold', name: 'Or Pur', price: 1500, primaryColor: '#fbbf24', secondaryColor: '#b45309', glowColor: '#fbbf24', pattern: 'metallic', rarity: 'RARE', description: 'La marque du luxe.' },
    { id: 'ss_silver', name: 'Argent Lunaire', price: 1200, primaryColor: '#e2e8f0', secondaryColor: '#94a3b8', glowColor: '#e2e8f0', pattern: 'metallic', rarity: 'RARE', description: 'Éclat de lune.' },
    { id: 'ss_bronze', name: 'Bronze Antique', price: 800, primaryColor: '#d97706', secondaryColor: '#78350f', glowColor: '#d97706', pattern: 'metallic', rarity: 'RARE', description: 'Style vintage.' },
    { id: 'ss_copper', name: 'Cuivre Brûlé', price: 900, primaryColor: '#ea580c', secondaryColor: '#9a3412', glowColor: '#ea580c', pattern: 'metallic', rarity: 'RARE', description: 'Conducteur d\'énergie.' },
    { id: 'ss_obsidian', name: 'Obsidienne', price: 1500, primaryColor: '#1e293b', secondaryColor: '#020617', glowColor: '#9d00ff', pattern: 'metallic', rarity: 'RARE', description: 'Verre volcanique.' },
    { id: 'ss_emerald_met', name: 'Émeraude Chrome', price: 1300, primaryColor: '#10b981', secondaryColor: '#064e3b', glowColor: '#10b981', pattern: 'metallic', rarity: 'RARE', description: 'Précieux et brillant.' },
    { id: 'ss_ruby_met', name: 'Rubis Chrome', price: 1300, primaryColor: '#ef4444', secondaryColor: '#7f1d1d', glowColor: '#ef4444', pattern: 'metallic', rarity: 'RARE', description: 'Éclat rubis.' },
    { id: 'ss_zebra', name: 'Zèbre Néon', price: 1000, primaryColor: '#ffffff', secondaryColor: '#000000', glowColor: '#ffffff', pattern: 'stripes', rarity: 'RARE', description: 'Rayures élégantes.' },
    { id: 'ss_tiger', name: 'Tigre Cyber', price: 1200, primaryColor: '#ff9d00', secondaryColor: '#000000', glowColor: '#ff9d00', pattern: 'stripes', rarity: 'RARE', description: 'Prédateur néon.' },
    { id: 'ss_checker', name: 'Damier Rétro', price: 1000, primaryColor: '#ffffff', secondaryColor: '#333333', glowColor: '#00f3ff', pattern: 'checker', rarity: 'RARE', description: 'Arcade classique.' },
    { id: 'ss_leopard', name: 'Léopard Cyan', price: 1500, primaryColor: '#00f3ff', secondaryColor: '#000000', glowColor: '#00f3ff', pattern: 'dots', rarity: 'EPIC', description: 'Agilité tachetée.' },
    { id: 'ss_dots_pink', name: 'Pois Flash', price: 1100, primaryColor: '#ff00ff', secondaryColor: '#ffffff', glowColor: '#ff00ff', pattern: 'dots', rarity: 'RARE', description: 'Look pop.' },
    { id: 'ss_army', name: 'Camouflage Cyber', price: 1400, primaryColor: '#22c55e', secondaryColor: '#064e3b', glowColor: '#22c55e', pattern: 'grid', rarity: 'RARE', description: 'Invisible sur la grille.' },
    { id: 'ss_snake_skin', name: 'Écailles Vrai', price: 2000, primaryColor: '#10b981', secondaryColor: '#facc15', glowColor: '#10b981', pattern: 'checker', rarity: 'EPIC', description: 'Comme un vrai.' },
    { id: 'ss_candy', name: 'Sucre d\'Orge', price: 1800, primaryColor: '#ff0000', secondaryColor: '#ffffff', glowColor: '#ff0000', pattern: 'stripes', rarity: 'EPIC', description: 'Délicieusement rapide.' },
    { id: 'ss_galaxy', name: 'Galaxie Profonde', price: 3500, primaryColor: '#312e81', secondaryColor: '#1e1b4b', glowColor: '#a855f7', pattern: 'pulse', rarity: 'EPIC', description: 'Poussière d\'étoiles.' },
    { id: 'ss_nebula', name: 'Nébuleuse', price: 4000, primaryColor: '#ec4899', secondaryColor: '#1e1b4b', glowColor: '#ec4899', pattern: 'pulse', rarity: 'EPIC', description: 'Gaz stellaire.' },
    { id: 'ss_supernova', name: 'Supernova', price: 4500, primaryColor: '#fbbf24', secondaryColor: '#ef4444', glowColor: '#fbbf24', pattern: 'pulse', rarity: 'EPIC', description: 'Explosion cosmique.' },
    { id: 'ss_blackhole', name: 'Trou Noir', price: 5000, primaryColor: '#000000', secondaryColor: '#312e81', glowColor: '#00f3ff', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Rien ne s\'échappe.' },
    { id: 'ss_starlight', name: 'Étoilé', price: 3800, primaryColor: '#ffffff', secondaryColor: '#0f172a', glowColor: '#ffffff', pattern: 'dots', rarity: 'EPIC', description: 'Ciel de nuit.' },
    { id: 'ss_mars', name: 'Planète Rouge', price: 3200, primaryColor: '#7f1d1d', secondaryColor: '#f87171', glowColor: '#ef4444', pattern: 'pulse', rarity: 'EPIC', description: 'Vibes martiennes.' },
    { id: 'ss_jupiter', name: 'Jupiter', price: 3500, primaryColor: '#b45309', secondaryColor: '#d97706', glowColor: '#facc15', pattern: 'stripes', rarity: 'EPIC', description: 'La géante gazeuse.' },
    { id: 'ss_magma', name: 'Magma Ardent', price: 6500, primaryColor: '#ef4444', secondaryColor: '#ea580c', glowColor: '#ef4444', pattern: 'pulse', rarity: 'LEGENDARY', description: 'La lave qui coule.' },
    { id: 'ss_ice_peak', name: 'Glace Éternelle', price: 6500, primaryColor: '#22d3ee', secondaryColor: '#ffffff', glowColor: '#22d3ee', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Froid absolu.' },
    { id: 'ss_thunder', name: 'Foudre Bleue', price: 7000, primaryColor: '#00f3ff', secondaryColor: '#1e3a8a', glowColor: '#ffffff', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Électrisant.' },
    { id: 'ss_toxic_waste', name: 'Déchet Toxique', price: 6000, primaryColor: '#4ade80', secondaryColor: '#064e3b', glowColor: '#4ade80', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Radioactif.' },
    { id: 'ss_holy', name: 'Lueur Divine', price: 8500, primaryColor: '#fffbeb', secondaryColor: '#fef3c7', glowColor: '#facc15', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Lumière pure.' },
    { id: 'ss_chaos', name: 'Ombre du Chaos', price: 8500, primaryColor: '#000000', secondaryColor: '#7f1d1d', glowColor: '#ef4444', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Destruction.' },
    { id: 'ss_forest_spirit', name: 'Esprit de Forêt', price: 7500, primaryColor: '#10b981', secondaryColor: '#064e3b', glowColor: '#34d399', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Énergie vitale.' },
    { id: 'ss_rainbow_flow', name: 'Flux Chroma', price: 15000, primaryColor: '#ff0000', secondaryColor: '#ffffff', glowColor: '#00f3ff', pattern: 'rainbow', rarity: 'LEGENDARY', description: 'Toutes les fréquences.' },
    { id: 'ss_diamond_core', name: 'Cœur de Diamant', price: 20000, primaryColor: '#ffffff', secondaryColor: '#bae6fd', glowColor: '#38bdf8', pattern: 'metallic', rarity: 'LEGENDARY', description: 'Indestructible.' },
    { id: 'ss_void', name: 'Le Vide', price: 25000, primaryColor: '#000000', secondaryColor: '#000000', glowColor: '#ffffff', pattern: 'pulse', rarity: 'LEGENDARY', description: 'La fin de tout.' },
    { id: 'ss_cyber_pulse', name: 'Pulse Cyberpunk', price: 18000, primaryColor: '#ff00ff', secondaryColor: '#00f3ff', glowColor: '#ff00ff', pattern: 'grid', rarity: 'LEGENDARY', description: 'Future Noir.' },
    { id: 'ss_golden_dragon', name: 'Dragon d\'Or', price: 50000, primaryColor: '#fbbf24', secondaryColor: '#d97706', glowColor: '#fbbf24', pattern: 'checker', rarity: 'LEGENDARY', description: 'Le souverain de l\'arène.' },
    { id: 'ss_plasma_storm', name: 'Tempête Plasma', price: 16000, primaryColor: '#a855f7', secondaryColor: '#06b6d4', glowColor: '#a855f7', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Énergie cinétique.' },
    { id: 'ss_matrix_core', name: 'Code Source', price: 17000, primaryColor: '#00ff00', secondaryColor: '#000000', glowColor: '#00ff00', pattern: 'grid', rarity: 'LEGENDARY', description: 'Vous voyez les lignes.' },
    { id: 'ss_blood_moon', name: 'Lune de Sang', price: 14000, primaryColor: '#450a0a', secondaryColor: '#ef4444', glowColor: '#ef4444', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Nuit de chasse.' },
    { id: 'ss_hologram', name: 'Hologramme', price: 19000, primaryColor: '#00f3ff', secondaryColor: '#ffffff', glowColor: '#00f3ff', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Immatériel.' },
    { id: 'ss_dark_fire', name: 'Feu Sombre', price: 22000, primaryColor: '#000000', secondaryColor: '#ea580c', glowColor: '#ea580c', pattern: 'pulse', rarity: 'LEGENDARY', description: 'Chaleur froide.' },
    { id: 'ss_infinity', name: 'Infini', price: 100000, primaryColor: '#ffffff', secondaryColor: '#000000', glowColor: '#ffffff', pattern: 'rainbow', rarity: 'LEGENDARY', description: 'L\'ultime trophée.' },
];

export const SLITHER_ACCESSORIES_CATALOG: SlitherAccessory[] = [
    { id: 'sa_none', name: 'Aucun', price: 0, type: 'HAT', color: 'transparent', description: 'Garder la tête libre.' },
    { id: 'sa_crown_gold', name: 'Couronne d\'Or', price: 5000, type: 'CROWN', color: '#ffe600', description: 'Le roi de l\'arène.' },
    { id: 'sa_crown_silver', name: 'Couronne d\'Argent', price: 4000, type: 'CROWN', color: '#e2e8f0', description: 'Éclat métallique.' },
    { id: 'sa_tiara_pink', name: 'Diadème Rose', price: 3500, type: 'TIARA', color: '#ff00ff', description: 'Élégance néon.' },
    { id: 'sa_tophat_black', name: 'Haut-de-forme Noir', price: 1500, type: 'HAT', color: '#111827', description: 'Un ver distingué.' },
    { id: 'sa_beret_red', name: 'Béret Rouge', price: 1000, type: 'BERET', color: '#ef4444', description: 'L\'artiste de l\'arène.' },
    { id: 'sa_cap_red', name: 'Casquette Rouge', price: 800, type: 'CAP', color: '#ef4444', description: 'Ver sportif.' },
    { id: 'sa_cowboy_brown', name: 'Chapeau Cowboy', price: 2500, type: 'COWBOY', color: '#78350f', description: 'Le shérif glissant.' },
    { id: 'sa_witch', name: 'Chapeau de Sorcier', price: 4500, type: 'WITCH', color: '#4c1d95', description: 'Magie noire.' },
    { id: 'sa_sunglasses_black', name: 'Cyber Lunettes', price: 1000, type: 'GLASSES', color: '#00f3ff', description: 'Style futuriste.' },
    { id: 'sa_ninja_red', name: 'Bandeau Ninja Rouge', price: 2000, type: 'NINJA', color: '#ef4444', description: 'Maître du camouflage.' },
    { id: 'sa_halo_gold', name: 'Auréole Céleste', price: 5000, type: 'HALO', color: '#ffe600', description: 'Ver angélique.' },
    { id: 'sa_horns_red', name: 'Cornes Démoniaques', price: 5000, type: 'HORNS', color: '#ef4444', description: 'Petit diable.' },
];
