import { TankSkin, TankAccessory } from '../types';

export const TANKS_CATALOG: TankSkin[] = [
    { id: 'tk_classic', name: 'Char Classique', price: 0, primaryColor: '#00d9ff', secondaryColor: '#0055ff', glowColor: '#00d9ff', description: 'Le blindage standard de la grille.' },
    { id: 'tk_crimson', name: 'Vanguard Rouge', price: 500, primaryColor: '#ff2d55', secondaryColor: '#990022', glowColor: '#ff2d55', description: 'Une peinture de guerre intimidante.' },
    { id: 'tk_emerald', name: 'Sentinelle Vert', price: 500, primaryColor: '#00ff9d', secondaryColor: '#006644', glowColor: '#00ff9d', description: 'Pour se fondre dans le Cyber-Forest.' },
    { id: 'tk_electric', name: 'Volt Chaser', price: 1500, primaryColor: '#ffff00', secondaryColor: '#ff9d00', glowColor: '#ffff00', description: 'Chargé à haute tension.', isAnimated: true },
    { id: 'tk_stealth', name: 'Shadow Ghost', price: 2000, primaryColor: '#444444', secondaryColor: '#000000', glowColor: '#ffffff', description: 'Presque invisible dans les ombres.' },
    { id: 'tk_cyber', name: 'Synthwave', price: 3000, primaryColor: '#ff00ff', secondaryColor: '#9d00ff', glowColor: '#ff00ff', description: 'Le style 80s ultime.' },
    { id: 'tk_gold', name: 'Royal Armor', price: 10000, primaryColor: '#ffe600', secondaryColor: '#ff9d00', glowColor: '#ffe600', description: 'L\'armure des champions de l\'arène.', isAnimated: true },
    { id: 'tk_plasma', name: 'Noyau Plasma', price: 7500, primaryColor: '#00f3ff', secondaryColor: '#ff00ff', glowColor: '#00f3ff', description: 'Réacteur énergétique instable.', isAnimated: true },
    { id: 'tk_void', name: 'Néant Obscur', price: 15000, primaryColor: '#1e1b4b', secondaryColor: '#000000', glowColor: '#9d00ff', description: 'Venu des confins du vide.', isAnimated: true }
];

export const TANK_ACCESSORIES_CATALOG: TankAccessory[] = [
    { id: 'ta_none', name: 'Aucun', price: 0, type: 'flag', colors: [], rarity: 'COMMON', description: 'Pas de fioritures.' },
    { id: 'ta_flag_fr', name: 'Drapeau France', price: 400, type: 'flag', colors: ['#0055A4', '#FFFFFF', '#EF4135'], svg: 'PHN2ZyB2aWV3Qm94PSIwIDAgMyAyIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0wIDBoM3YySDB6Ii8+PHBhdGggZmlsbD0iIzAwNTVBNCIgZD0iTTAgMGgxdjJIMHoiLz48cGF0aCBmaWxsPSIjRUY0MTM1IiBkPSJNMCAwaDF2MkgweiIgZmlsbD0iIzAwNTVBNCIvPjxwYXRoIGQ9Ik0yIDBoMXYySDJ6Ii8+PC9zdmc+', rarity: 'RARE', description: 'Fierté tricolore.' },
    { id: 'ta_flag_it', name: 'Drapeau Italie', price: 400, type: 'flag', colors: ['#009246', '#FFFFFF', '#CE2B37'], svg: 'PHN2ZyB2aWV3Qm94PSIwIDAgMyAyIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0wIDBoM3YySDB6Ii8+PHBhdGggZmlsbD0iIzAwOTI0NiIgZD0iTTAgMGgxdjJIMHoiLz48cGF0aCBmaWxsPSIjQ0UyQjM3IiBkPSJNMhAwSDF2MkgweiIvPjwvc3ZnPg==', rarity: 'RARE', description: 'Forza sur le champ de bataille.' },
    { id: 'ta_flag_de', name: 'Drapeau Allemagne', price: 400, type: 'flag', colors: ['#000000', '#DD0000', '#FFCE00'], svg: 'PHN2ZyB2aWV3Qm94PSIwIDAgNSAzIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIGQ9Ik0wIDBoNXYzSDB6Ii8+PHBhdGggZD0iTTAgMWg1djFIMHoiIGZpbGw9IiNEMDAiLz48cGF0aCBkPSJNMCAyaDV2MUgweiIgZmlsbD0iI0ZGQ0UwMCIvPjwvc3ZnPg==', rarity: 'RARE', description: 'La rigueur du combat.' },
    { id: 'ta_flag_es', name: 'Drapeau Espagne', price: 400, type: 'flag', colors: ['#AA151B', '#F1BF00', '#AA151B'], svg: 'PHN2ZyB2aWV3Qm94PSIwIDAgMyAyIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIGZpbGw9IiNBQTE1MUIiIGQ9Ik0wIDBoM3YySDB6Ii8+PHBhdGggZmlsbD0iI0YxQkYwMCIgZD0iTTAgLjVoM3YxSDB6Ii8+PC9zdmc+', rarity: 'RARE', description: 'La passion du néon.' },
    { id: 'ta_flag_us', name: 'Drapeau USA', price: 400, type: 'flag', colors: ['#3C3B6E', '#FFFFFF', '#B22234'], svg: 'PHN2ZyB2aWV3Qm94PSIwIDAgMTkgMTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjE5IiBoZWlnaHQ9IjEwIiBmaWxsPSIjQjIyMjM0Ii8+PHBhdGggc3Ryb2tlPSIjZmZmIiBzdHJva2Utd2lkdGg9IjIiIGQ9Ik0wIDFoMTkgTTAgNWgxOSBNMCA5aDE5Ii8+PHJlY3Qgd2lkdGg9IjkuNSIgaGVpZ2h0PSI1IiBmaWxsPSIjM0MzQjZFIi8+PHRleHQgeD0iNC43NSIgeT0iMy41IiBmb250LWZhbWlseT0ibW9ub3NwYWNlIiBmb250LXNpemU9IjMiIGZpbGw9IiNmZmYiIHRleHQtYW5jaG9yPSJtaWRkbGUiPuKQtjwvdGV4dD48L3N2Zz4=', rarity: 'RARE', description: 'Stars and Stripes.' },
    { id: 'ta_flag_jp', name: 'Drapeau Japon', price: 400, type: 'flag', colors: ['#FFFFFF', '#BC002D'], svg: 'PHN2ZyB2aWV3Qm94PSIwIDAgMyAyIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIzIiBoZWlnaHQ9IjIiIGZpbGw9IiNmZmYiLz48Y2lyY2xlIGN4PSIxLjUiIGN5PSIxIiByPSIuNiIgZmlsbD0iI0JDMDAyRCIvPjwvc3ZnPg==', rarity: 'RARE', description: 'Le soleil levant.' },
    { id: 'ta_flag_br', name: 'Drapeau Brésil', price: 400, type: 'flag', colors: ['#009739', '#FEDD00', '#012169'], svg: 'PHN2ZyB2aWV3Qm94PSIwIDAgMTAgNyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAiIGhlaWdodD0iNyIgZmlsbD0iIzAwOTc0MCIvPjxwYXRoIGQ9Ik01IC41TC44IDMuNSA1IDYuNWw0LjItM3oiIGZpbGw9IiNGRUREMDAiLz48Y2lyY2xlIGN4PSI1IiBjeT0iMy41IiByPSIxLjc1IiBmaWxsPSIjMDEyMTY5Ii8+PC9zdmc+', rarity: 'RARE', description: 'Le rythme de l\'arène.' },
    { id: 'ta_flag_be', name: 'Drapeau Belgique', price: 400, type: 'flag', colors: ['#000000', '#FAE042', '#ED2939'], svg: 'PHN2ZyB2aWV3Qm94PSIwIDAgMyAyIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIGQ9Ik0wIDBoMXYySDB6IiBmaWxsPSIjMDAwIi8+PHBhdGggZD0iTTEgMGgxdjJIMHoiIGZpbGw9IiNGQUUwNDIiLz48cGF0aCBkPSJNMhAwSDF2MkgweiIgZmlsbD0iI0VEMjkzOSIvPjwvc3ZnPg==', rarity: 'RARE', description: 'L\'union fait la force sur le serveur.' },
    { id: 'ta_flag_pirate', name: 'Jolly Roger', price: 1200, type: 'flag', colors: ['#000000', '#FFFFFF'], svg: 'PHN2ZyB2aWV3Qm94PSIwIDAgMjQgMjQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSJibGFjayIvPjxwYXRoIGQ9Ik0xMiwyQTEwLDEwIDAgMCwwIDIsMTJBMTAsMTAgMCAwLDAgMTIsMjJBMTAsMTAgMCAwLDAgMjIsMTJBMTAsMTAgMCAwLDAgMTIsMk0xMiw0QTgsOCAwIDAsMSAyMCwxMkMyMCwxMy4xMyAxOS42NCwxNC4xOCAxOSwxNUg1QzQuMzYsMTQuMTggNCwxMy4xMyA0LDEyQTgsOCAwIDAsMSAxMiw0TTksOUEyLDIgMCAwLDEgNywxMUEyLDIgMCAwLDEgNSw5QTIsMiAwIDAsMSA5LDlNMTUsOUEyLDIgMCAwLDEgMTMsMTFBMiwyIDAgMCwxIDExLDlBMiwyIDAgMCwxIDE1LDlNOSwxNEgxNVYxNkg5VjE0WiIgZmlsbD0id2hpdGUiIC8+PC9zdmc+', rarity: 'EPIC', description: 'Pas de quartier !' },
    { id: 'ta_flag_neon', name: 'Bannière Néon', price: 2500, type: 'flag', colors: ['#00f3ff', '#ff00ff', '#9d00ff'], rarity: 'LEGENDARY', description: 'L\'emblème ultime de l\'Arcade.' },
];